$mod = SUPER

# screen
bind = $mod, K, exec, hyprlock

# Screen recording
bind = SUPER, S, exec, wf-recorder -o $(hyprctl monitors -j | jq -r '.[] | select(.focused) | .name') -f ~/Videos/$(date +%Y%m%d_%H%M%S).mp4
bind = SUPER SHIFT, S, exec, pkill wf-recorder
bind = SUPER, E, exec, wf-recorder -g "$(slurp)" -f ~/Videos/$(date +%Y%m%d_%H%M%S).mp4
bind = SUPER SHIFT, E, exec, pkill wf-recorder

# apps
bind = $mod, RETURN, exec, ghostty
bind = $mod, D, exec, wofi --show drun --style ~/.config/wofi/style.css

# movement (vim style)
bind = $mod, Left,  movefocus, l
bind = $mod, Right, movefocus, r
bind = $mod, Up,    movefocus, u
bind = $mod, Down,  movefocus, d

# move windows
bind = $mod SHIFT, Left,  movewindow, l
bind = $mod SHIFT, Right, movewindow, r
bind = $mod SHIFT, Up,    movewindow, u
bind = $mod SHIFT, Down,  movewindow, d

# workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5

# resize windows
binde = $mod ALT, Left,  resizeactive, -40 0
binde = $mod ALT, Right, resizeactive, 40 0
binde = $mod ALT, Up,    resizeactive, 0 -40
binde = $mod ALT, Down,  resizeactive, 0 40

# useful
bind = $mod, Q, killactive
bind = $mod, SPACE, togglefloating
bind = $mod, M, fullscreen, 1    # maximize/restore toggle
bind = $mod, F, fullscreen, 0    # true fullscreen toggle

# startup
exec-once = snixembed --fork
exec-once = waybar
exec-once = dunst

input {
    kb_layout = us,ru,am
    kb_variant = ,,phonetic
    kb_options = grp:alt_shift_toggle
    follow_mouse = 2
}

general {
    gaps_in = 2
    gaps_out = 6
    border_size = 1
    layout = dwindle
}

decoration {
    rounding = 4
    active_opacity = 1.0
    inactive_opacity = 0.8

    blur {
        enabled = true
        size = 3
	passes = 2
    }
   
}

animations {
    enabled = true
}

env = WLR_NO_HARDWARE_CURSORS,1
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,Fusion
env = GTK_CSD,0
env = GTK_THEME,adw-gtk3-dark
