#!/bin/bash
#
# Interactive monitor setup for Hyprland
# Identifies monitors by flashing each one, then saves position config by serial number.
# Run this whenever you change your physical monitor arrangement.
#

set -e

CONF="$HOME/.config/hypr-local/monitors.conf"
mkdir -p "$HOME/.config/hypr-local"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

if ! command -v hyprctl &>/dev/null || ! hyprctl monitors &>/dev/null; then
    echo -e "${YELLOW}Hyprland is not running — start a session first.${NC}"
    exit 1
fi

# Gather connected monitors
mapfile -t names < <(hyprctl monitors -j | jq -r '.[].name')
mapfile -t serials < <(hyprctl monitors -j | jq -r '.[].serial')
mapfile -t descriptions < <(hyprctl monitors -j | jq -r '.[].description')
mapfile -t widths < <(hyprctl monitors -j | jq -r '.[].width')

count=${#names[@]}

if [ "$count" -lt 2 ]; then
    echo -e "${GREEN}Only one monitor detected — no arrangement needed.${NC}"
    echo "# Single monitor — auto placement" > "$CONF"
    exit 0
fi

echo ""
echo -e "  ${CYAN}Monitor Setup${NC}"
echo -e "  Found ${GREEN}$count${NC} monitors. I'll dim each one so you can identify it."
echo ""

# Build position labels based on monitor count
if [ "$count" -eq 2 ]; then
    positions=("left" "right")
elif [ "$count" -eq 3 ]; then
    positions=("left" "center" "right")
else
    positions=()
    for i in $(seq 1 "$count"); do
        positions+=("position $i (left to right)")
    done
fi

# For each position, ask which monitor it is
declare -A position_map  # position_index -> monitor_index
used=()

for pos_idx in "${!positions[@]}"; do
    pos_label="${positions[$pos_idx]}"
    echo -e "  Which monitor is on the ${GREEN}${pos_label}${NC}?"
    echo ""

    # List available (unassigned) monitors
    available=()
    for mon_idx in "${!names[@]}"; do
        skip=false
        for u in "${used[@]}"; do
            [ "$u" = "$mon_idx" ] && skip=true && break
        done
        $skip && continue
        available+=("$mon_idx")
    done

    # If only one left, auto-assign
    if [ "${#available[@]}" -eq 1 ]; then
        mon_idx="${available[0]}"
        position_map[$pos_idx]=$mon_idx
        used+=("$mon_idx")
        echo -e "  → Auto-assigned: ${descriptions[$mon_idx]}"
        echo ""
        continue
    fi

    # Flash each available monitor by toggling DPMS off/on
    for i in "${!available[@]}"; do
        mon_idx="${available[$i]}"
        num=$((i + 1))
        echo -e "  ${CYAN}[$num]${NC} Flashing ${names[$mon_idx]}..."

        # Turn off this monitor briefly
        hyprctl dispatch dpms off "${names[$mon_idx]}" &>/dev/null
        sleep 1.5
        hyprctl dispatch dpms on "${names[$mon_idx]}" &>/dev/null
        sleep 0.5
    done

    echo ""
    while true; do
        read -rp "  Which monitor flashed for ${pos_label}? [1-${#available[@]}]: " choice
        if [[ "$choice" =~ ^[0-9]+$ ]] && [ "$choice" -ge 1 ] && [ "$choice" -le "${#available[@]}" ]; then
            mon_idx="${available[$((choice - 1))]}"
            position_map[$pos_idx]=$mon_idx
            used+=("$mon_idx")
            echo -e "  → ${GREEN}${pos_label}${NC}: ${descriptions[$mon_idx]}"
            echo ""
            break
        fi
        echo "  Invalid choice, try again."
    done
done

# Generate monitors.conf using serial-based descriptions
echo "# Auto-generated by setup-monitors.sh — do not edit manually" > "$CONF"
echo "# Run setup-monitors.sh to reconfigure" >> "$CONF"
echo "" >> "$CONF"

x_offset=0
for pos_idx in $(seq 0 $((count - 1))); do
    mon_idx=${position_map[$pos_idx]}
    name="${names[$mon_idx]}"
    serial="${serials[$mon_idx]}"
    desc="${descriptions[$mon_idx]}"
    w="${widths[$mon_idx]}"

    # Use description (make+model+serial) for stable matching across port changes
    echo "monitor = desc:${desc}, preferred, ${x_offset}x0, 1" >> "$CONF"
    x_offset=$((x_offset + w))
done

echo ""
echo -e "  ${GREEN}Saved to ${CONF}${NC}"
echo ""
cat "$CONF"
echo ""

# Apply immediately
hyprctl reload &>/dev/null && echo -e "  ${GREEN}Hyprland reloaded.${NC}" || true
